title: Vuong Viet Linh # your name (or website title) here
logo: "/images/profile.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
  Hi, I'm Linh, a data enthusiast who loves to explore and learn new things about data analysis and data science. 
  <br>
  In this portfolio, you will find some of the projects that I have worked on, ranging from data visualization, machine learning, to data analysis. 
  <br>
  I hope you will find them interesting and informative. Thank you for visiting my portfolio!
  <a href="https://www.linkedin.com/in/linh-vuong-viet/">View My LinkedIn Profile</a> 
 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
